services:
  # Backend Web Service
  - type: web
    name: medical-cancer-detection-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: oregon
    plan: free # Or higher depending on ML model requirements
    healthCheckPath: /health/db
    envVars:
      - key: MONGO_URI
        sync: false # Set this in the Render Dashboard

  # Frontend Static Site
  - type: web
    name: medical-cancer-detection-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: medical-cancer-detection-backend
          envVarKey: RENDER_EXTERNAL_URL
